# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'oyun.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import random

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(518, 450)
        MainWindow.setMinimumSize(QtCore.QSize(518, 450))
        MainWindow.setMaximumSize(QtCore.QSize(518, 450))
        MainWindow.setMouseTracking(False)
        MainWindow.setTabletTracking(False)
        MainWindow.setIconSize(QtCore.QSize(24, 24))
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Triangular)
        MainWindow.setDockOptions(QtWidgets.QMainWindow.AllowTabbedDocks|QtWidgets.QMainWindow.AnimatedDocks)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(290, 80, 221, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Symbol")
        font.setPointSize(28)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 0, 0);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(80, 0, 61, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Emoji")
        font.setPointSize(26)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("")
        self.label_2.setScaledContents(False)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(0, 0, 521, 71))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(22)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(9)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("QLabel{\n"
"    \n"
"    \n"
"    background-color: qlineargradient(spread:repeat, x1:0, y1:0, x2:1, y2:0, stop:0.267045 rgba(255, 0, 201, 255), stop:1 rgba(167, 0, 218, 255));\n"
"    color: rgb(255, 255, 255);\n"
"    font: 75 italic 22pt \"MS Sans Serif\";\n"
"}")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(0, 80, 521, 51))
        self.label_4.setStyleSheet("QLabel{\n"
"    \n"
"    background-color: rgb(252, 255, 238);\n"
"    font: 75 italic 18pt \"MS Sans Serif\";\n"
"    \n"
"    color: rgb(0, 0, 0);\n"
"\n"
"}")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 150, 471, 81))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Emoji")
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("QLabel{\n"
"    background-color:;\n"
"    background-color: rgb(75, 225, 255);\n"
"    border-radius:20px;\n"
"}\n"
"")
        self.label_5.setScaledContents(True)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.spinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox.setGeometry(QtCore.QRect(60, 250, 381, 41))
        self.spinBox.setStyleSheet("QSpinBox{\n"
"    \n"
"    \n"
"    border-radius:20px;\n"
"    \n"
"}")
        self.spinBox.setWrapping(False)
        self.spinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox.setSuffix("")
        self.spinBox.setMinimum(1)
        self.spinBox.setMaximum(100)
        self.spinBox.setProperty("value", 1)
        self.spinBox.setDisplayIntegerBase(10)
        self.spinBox.setObjectName("spinBox")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(90, 310, 311, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Symbol")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton.setFont(font)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.WhatsThisCursor))
        self.pushButton.setStyleSheet("QPushButton{\n"
"    \n"
"    background-color: qlineargradient(spread:repeat, x1:0, y1:0, x2:1, y2:0, stop:0.267045 rgba(255, 0, 201, 255), stop:1 rgba(167, 0, 218, 255));\n"
"    color: rgb(255, 255, 255);\n"
"    \n"
"    font: 20pt \"Segoe UI Symbol\";\n"
"    border-radius:20px;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(130, 370, 231, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Symbol")
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"    \n"
"    background-color: rgb(162, 162, 162);\n"
"    color: rgb(255, 255, 255);\n"
"    \n"
"    font: 15pt \"Segoe UI Symbol\";\n"
"    border-radius:20px;\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(20, 420, 471, 20))
        self.label_6.setStyleSheet("color: rgb(255, 0, 0);\n"
"font: 75 italic 18pt \"MS Sans Serif\";")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.label_3.raise_()
        self.label_2.raise_()
        self.label_4.raise_()
        self.label.raise_()
        self.label_5.raise_()
        self.spinBox.raise_()
        self.pushButton.raise_()
        self.pushButton_2.raise_()
        self.label_6.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        
        self.tutulan_sayi = random.randint(1, 100)
        self.kalan_haklar = 6
        self.tahmin_listesi = []
        self.pushButton.clicked.connect(self.tahmin_et)
        self.pushButton_2.clicked.connect(self.yeniden_basla)

        self.retranslateUi(MainWindow)

        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def tahmin_et(self):
        tahmin_sayisi = self.spinBox.value()
        
        if tahmin_sayisi == self.tutulan_sayi:
                self.label_5.setText("✅Tebrikler! Doğru tahmin ettiniz.")
                self.pushButton.setEnabled(False)
                self.spinBox.setEnabled(False)
        elif tahmin_sayisi < self.tutulan_sayi:
                self.label_5.setText("⬆️⬆️ Daha yüksek bir sayı deneyin.")
                self.kalan_haklar -= 1
                self.label.setText(self.kalan_haklar * "❤")
        else:
                self.label_5.setText("⬇️⬇️ Daha düşük bir sayı deneyin.")
                self.kalan_haklar -= 1
                self.label.setText(self.kalan_haklar * "❤")

        
        self.tahmin_listesi.append(tahmin_sayisi)
        self.label_6.setText("Tahminler: " + " - ".join(map(str , self.tahmin_listesi)))


        if self.kalan_haklar == 0:
                self.label_5.setText(f"❌Haklarınız bitti! Doğru sayı {self.tutulan_sayi} idi. Yeniden başlayın.")
                self.pushButton.setEnabled(False)
                self.spinBox.setEnabled(False)

    def yeniden_basla(self):
        # 1. Değişkenleri sıfırla
        self.kalan_haklar = 6
        self.tutulan_sayi = random.randint(1, 100)
        self.tahmin_listesi = []

        
        # 2. Arayüzü sıfırla
        self.label.setText("❤" * self.kalan_haklar)
        self.label_5.setText("1 ile 100 arasında bir sayı tuttum! Tahmin et bakalım 🎯")
        self.label_6.setText("")
        self.spinBox.setValue(1) # Spinbox'ı 1'e ayarla
        
        # 3. Butonları ve spinbox'ı tekrar aktif hale getir
        self.pushButton.setEnabled(True)
        self.spinBox.setEnabled(True)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Sayı Tahmin Oyunu"))
        self.label.setText(_translate("MainWindow", "❤❤❤❤❤❤"))
        self.label_2.setText(_translate("MainWindow", "🎮 "))
        self.label_3.setText(_translate("MainWindow", "Sayı Tahmin Oyunu"))
        self.label_4.setText(_translate("MainWindow", "       Kalan Haklar:"))
        self.label_5.setText(_translate("MainWindow", "1 ile 100 arasında bir sayı tuttum! Tahmin et bakalım 🎯"))
        self.pushButton.setText(_translate("MainWindow", "🎯 Tahmin Et"))
        self.pushButton_2.setText(_translate("MainWindow", "↻ Yeniden Başla"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
